title: DevLabs — Kunal Kumar
theme: jekyll-theme-cayman
url: "https://kumarvariable.github.io"
baseurl: "/devlabs"
email: nkunal@aol.com
linkedin: https://www.linkedin.com/in/nkunal/
description: Multi-project hub for my experiments and case studies.
